# This is a basic workflow to help you get started with Actions
name: Import

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: '5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Github Action for curl
      uses: wei/curl@v1.1.1
      with:
        args: -X POST "https://api.tinybird.co/v0/datasources?token=${{ secrets.test_token }}&name=stock_sam&mode=append&url=https://storage.googleapis.com/tinybird-demo/stocks/stock_1998.csv"
